# Nama Aplikasi
spring.application.name=productapi

# ==========================================
# KONFIGURASI PORT SERVER
# ==========================================
# Mengubah port default dari 8080 menjadi 9090
server.port=9090

# ==========================================
# KONFIGURASI DATABASE MYSQL
# ==========================================
# Menggunakan database "product_db2"
spring.datasource.url=jdbc:mysql://localhost:3306/product_db2?createDatabaseIfNotExist=true&serverTimezone=UTC

# Username dan Password MySQL Anda (Bawaan XAMPP)
spring.datasource.username=root
spring.datasource.password=

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# KONFIGURASI JPA / HIBERNATE
# ==========================================
# Hibernate akan otomatis membuat/memperbarui tabel di database product_db2
spring.jpa.hibernate.ddl-auto=update

# Menampilkan query SQL di console/terminal
spring.jpa.show-sql=true

# Merapikan tampilan query SQL
spring.jpa.properties.hibernate.format_sql=true
# ==========================================
# KONFIGURASI SWAGGER / OPENAPI
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Menggunakan dialek MySQL 8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect